[package]
name = "oms"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0.1"
rusqlite = "0.32.1"
lazy_static = "1.4.0"
r2d2 = "0.8.9"
r2d2_sqlite = "0.25.0"

thiserror = "1.0"
log = "0.4"